#!/bin/bash
# /opt/blocklist/generate-zone.sh
#
# Generates rbldnsd zone files from the blocklist MariaDB database.
# Called by reload-rbldnsd.sh before sending SIGHUP to rbldnsd.
#
# Writes:
#   /var/lib/rbldns/ips.txt      — ip4set zone (IPv4 addresses and CIDR ranges)
#   /var/lib/rbldns/domains.txt  — dnset zone  (hostnames and domains)
#
# Setup:
#   1. Place this file at /opt/blocklist/generate-zone.sh
#   2. chmod +x /opt/blocklist/generate-zone.sh
#   3. Edit the DB_* variables below to match your environment
#   4. Ensure the script user can write to /var/lib/rbldns/

set -euo pipefail

# ── Database connection ────────────────────────────────────────────────────
DB_HOST="45.58.55.152"
DB_PORT="3306"
DB_NAME="blocklist"
DB_USER="blocklist_app"
# Password via .my.cnf or environment — never hardcode here.
# Create /root/.my.cnf (or the home dir of the user running this script):
#   [client]
#   password=your-password
# chmod 600 ~/.my.cnf

# ── Zone file paths ────────────────────────────────────────────────────────
ZONE_DIR="/var/lib/rbldns"
IPS_FILE="$ZONE_DIR/ips.txt"
DOMAINS_FILE="$ZONE_DIR/domains.txt"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
LOGFILE="/var/log/rbldnsd-reload.log"

# ── Zone SOA/NS config ─────────────────────────────────────────────────────
# rbldnsd SOA/NS format (all times in seconds, no BIND shorthand):
#   $SOA <ttl> <origin> <hostmaster> <serial> <refresh> <retry> <expire> <minttl>
#   $NS  <ttl> <nameserver>
# Serial 0 is intentional — rbldnsd substitutes the file's mtime automatically.
SOA_LINE="\$SOA 3600 ns1.dnsbl.whizardries.com. hostmaster.whizardries.com. 0 3600 600 86400 3600"
NS_LINE="\$NS 3600 ns1.dnsbl.whizardries.com."

MYSQL="mariadb --batch --skip-column-names -h $DB_HOST -P $DB_PORT -u $DB_USER $DB_NAME"

# ── Verify zone directory exists and is writable ───────────────────────────
if [ ! -d "$ZONE_DIR" ]; then
    echo "[$TIMESTAMP] ERROR: Zone directory $ZONE_DIR does not exist" >> "$LOGFILE"
    exit 1
fi

if [ ! -w "$ZONE_DIR" ]; then
    echo "[$TIMESTAMP] ERROR: Zone directory $ZONE_DIR is not writable" >> "$LOGFILE"
    exit 1
fi

# ── Generate ips.txt (ip4set format) ──────────────────────────────────────
# ip4set format:
#   # comment lines start with hash
#   :127.0.0.2:Listed in dnsbl.whizardries.com    (default return value line)
#   192.0.2.1                                       (individual IP)
#   192.0.2.0/24                                    (CIDR range)

{
    echo "# Generated by generate-zone.sh at $TIMESTAMP"
    echo "# Do not edit manually — changes will be overwritten on next reload"
    echo "$SOA_LINE"
    echo "$NS_LINE"
    echo ":127.0.0.2:Listed in dnsbl.whizardries.com"
    echo ""

    $MYSQL << 'SQL'
SELECT
    CASE
        WHEN entry_type = 'cidr' THEN CONCAT(address, '/', cidr)
        ELSE address
    END AS record
FROM ip
WHERE active = 1
  AND entry_type IN ('ip', 'cidr')
ORDER BY address, cidr;
SQL

} > "${IPS_FILE}.tmp"

# Atomic replace — never leave rbldnsd reading a half-written file
mv "${IPS_FILE}.tmp" "$IPS_FILE"

IP_COUNT=$($MYSQL -e "SELECT COUNT(*) FROM ip WHERE active = 1 AND entry_type IN ('ip','cidr');" 2>/dev/null || echo "?")
echo "[$TIMESTAMP] Generated $IPS_FILE ($IP_COUNT active IP/CIDR entries)" >> "$LOGFILE"

# ── Generate domains.txt (dnset format) ───────────────────────────────────
# dnset format:
#   # comment lines start with hash
#   :127.0.0.2:Listed in dnsbl.whizardries.com    (default return value line)
#   spammer.example.com                             (exact hostname)
#   .example.com                                    (wildcard — matches all of example.com)

{
    echo "# Generated by generate-zone.sh at $TIMESTAMP"
    echo "# Do not edit manually — changes will be overwritten on next reload"
    echo "$SOA_LINE"
    echo "$NS_LINE"
    echo ":127.0.0.2:Listed in dnsbl.whizardries.com"
    echo ""

    $MYSQL << 'SQL'
SELECT address
FROM ip
WHERE active = 1
  AND entry_type = 'hostname'
ORDER BY address;
SQL

} > "${DOMAINS_FILE}.tmp"

mv "${DOMAINS_FILE}.tmp" "$DOMAINS_FILE"

DOMAIN_COUNT=$($MYSQL -e "SELECT COUNT(*) FROM ip WHERE active = 1 AND entry_type = 'hostname';" 2>/dev/null || echo "?")
echo "[$TIMESTAMP] Generated $DOMAINS_FILE ($DOMAIN_COUNT active hostname entries)" >> "$LOGFILE"

exit 0
