#!/bin/bash
# /opt/blocklist/generate-zone.sh
#
# Generates rbldnsd zone files from the blocklist MariaDB database.
# Called by reload-rbldnsd.sh before sending SIGHUP to rbldnsd.
#
# Writes:
#   $ZONE_DIR/ips.txt      — ip4set zone (IPv4 addresses and CIDR ranges)
#   $ZONE_DIR/domains.txt  — dnset zone  (hostnames and domains)
#
# Setup:
#   1. Place this file at /opt/blocklist/generate-zone.sh
#   2. chmod +x /opt/blocklist/generate-zone.sh
#   3. Copy blocklist.conf.example to /opt/blocklist/blocklist.conf and fill in values
#   4. chmod 640 /opt/blocklist/blocklist.conf
#   5. chown root:www-data /opt/blocklist/blocklist.conf

set -euo pipefail

CONF="/opt/blocklist/blocklist.conf"

if [ ! -f "$CONF" ]; then
    echo "ERROR: $CONF not found. Copy blocklist.conf.example and fill in your values." >&2
    exit 1
fi

# shellcheck source=/dev/null
. "$CONF"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
IPS_FILE="$ZONE_DIR/ips.txt"
DOMAINS_FILE="$ZONE_DIR/domains.txt"

SOA_LINE="\$SOA ${SOA_TTL} ${SOA_ORIGIN} ${SOA_HOSTMASTER} 0 ${SOA_REFRESH} ${SOA_RETRY} ${SOA_EXPIRE} ${SOA_MINTTL}"
NS_LINE="\$NS ${NS_TTL} ${NS_HOST}"

MYSQL="mariadb --batch --skip-column-names -h ${DB_HOST} -P ${DB_PORT} -u ${DB_USER} -p${DB_PASS} ${DB_NAME}"

# ── Verify zone directory ──────────────────────────────────────────────────
if [ ! -d "$ZONE_DIR" ]; then
    echo "[$TIMESTAMP] ERROR: Zone directory $ZONE_DIR does not exist" >> "$RELOAD_LOG"
    exit 1
fi

if [ ! -w "$ZONE_DIR" ]; then
    echo "[$TIMESTAMP] ERROR: Zone directory $ZONE_DIR is not writable" >> "$RELOAD_LOG"
    exit 1
fi

# ── Generate ips.txt (ip4set format) ──────────────────────────────────────
{
    echo "# Generated by generate-zone.sh at $TIMESTAMP"
    echo "# Do not edit manually — changes will be overwritten on next reload"
    echo "$SOA_LINE"
    echo "$NS_LINE"
    echo ":${DNSBL_RETURN}:Listed in ${DNSBL_ZONE}"
    echo ""

    $MYSQL << 'SQL'
SELECT
    CASE
        WHEN entry_type = 'cidr' THEN CONCAT(address, '/', cidr)
        ELSE address
    END AS record
FROM ip
WHERE active = 1
  AND entry_type IN ('ip', 'cidr')
ORDER BY address, cidr;
SQL

} > "${IPS_FILE}.tmp"

mv "${IPS_FILE}.tmp" "$IPS_FILE"

IP_COUNT=$($MYSQL -e "SELECT COUNT(*) FROM ip WHERE active = 1 AND entry_type IN ('ip','cidr');" 2>/dev/null || echo "?")
echo "[$TIMESTAMP] Generated $IPS_FILE ($IP_COUNT active IP/CIDR entries)" >> "$RELOAD_LOG"

# ── Generate domains.txt (dnset format) ───────────────────────────────────
{
    echo "# Generated by generate-zone.sh at $TIMESTAMP"
    echo "# Do not edit manually — changes will be overwritten on next reload"
    echo "$SOA_LINE"
    echo "$NS_LINE"
    echo ":${DNSBL_RETURN}:Listed in ${DNSBL_ZONE}"
    echo ""

    $MYSQL << 'SQL'
SELECT address
FROM ip
WHERE active = 1
  AND entry_type = 'hostname'
ORDER BY address;
SQL

} > "${DOMAINS_FILE}.tmp"

mv "${DOMAINS_FILE}.tmp" "$DOMAINS_FILE"

DOMAIN_COUNT=$($MYSQL -e "SELECT COUNT(*) FROM ip WHERE active = 1 AND entry_type = 'hostname';" 2>/dev/null || echo "?")
echo "[$TIMESTAMP] Generated $DOMAINS_FILE ($DOMAIN_COUNT active hostname entries)" >> "$RELOAD_LOG"

exit 0
